# Generated by Django 2.0.4 on 2018-04-16 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Size', models.CharField(default='M', max_length=2)),
                ('StokeSize', models.IntegerField(default=0)),
                ('Price', models.FloatField(default=0)),
                ('kind', models.CharField(default='Jacket', max_length=10)),
                ('image', models.ImageField(blank=True, max_length=45, upload_to='uploads/jackets/')),
            ],
        ),
        migrations.CreateModel(
            name='Pant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Size', models.CharField(default='M', max_length=2)),
                ('StokeSize', models.IntegerField(default=0)),
                ('Price', models.FloatField(default=0)),
                ('kind', models.CharField(default='Pant', max_length=10)),
                ('image', models.ImageField(blank=True, max_length=45, upload_to='uploads/pants/')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Size', models.CharField(default='M', max_length=2)),
                ('StokeSize', models.IntegerField(default=0)),
                ('Price', models.FloatField(default=0)),
                ('kind', models.CharField(default='Shirt', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='T_shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Size', models.CharField(default='M', max_length=2)),
                ('StokeSize', models.IntegerField(default=0)),
                ('Price', models.FloatField(default=0)),
                ('kind', models.CharField(default='T-Shirt', max_length=10)),
                ('image', models.ImageField(blank=True, max_length=45, upload_to='uploads/t_shirts/')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='man.Question'),
        ),
    ]
