# Generated by Django 2.0.4 on 2018-04-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=45, upload_to='uploads/slides/')),
                ('Comments', models.CharField(max_length=200)),
                ('link', models.URLField(default='#')),
            ],
        ),
    ]
