# Generated by Django 2.0.4 on 2018-04-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0002_slides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Kind', models.CharField(default='Accessories', max_length=10)),
                ('Name', models.CharField(max_length=100)),
                ('Size', models.CharField(default='M', max_length=2)),
                ('StokeSize', models.IntegerField(default=0)),
                ('Price', models.FloatField(default=0)),
                ('Image', models.ImageField(blank=True, max_length=45, upload_to='uploads/t_shirts/')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RenameField(
            model_name='jacket',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='pant',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='slides',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='slides',
            old_name='link',
            new_name='Link',
        ),
        migrations.RenameField(
            model_name='t_shirt',
            old_name='image',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='jacket',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='pant',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='t_shirt',
            name='kind',
        ),
        migrations.AddField(
            model_name='jacket',
            name='Kind',
            field=models.CharField(default='Jackets', max_length=10),
        ),
        migrations.AddField(
            model_name='pant',
            name='Kind',
            field=models.CharField(default='Pants', max_length=10),
        ),
        migrations.AddField(
            model_name='shirt',
            name='Kind',
            field=models.CharField(default='Shirts', max_length=10),
        ),
        migrations.AddField(
            model_name='t_shirt',
            name='Kind',
            field=models.CharField(default='T-Shirts', max_length=10),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
